import type { Metadata } from 'next'
import './globals.css'
import Sidebar from './_components/sidebar'
import { Inter } from 'next/font/google'
import { ThemeProvider } from './_components/theme-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({
  subsets: ['latin'],
  display: 'auto',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <div className="flex h-full gap-8">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Sidebar />
            {children}
          </ThemeProvider>
        </div>
      </body>
    </html>
  )
}
